Is catching an error with `try ... catch` a better practice than catching an error with proper analysis/error check? For instance, removing from an empty list: Does surround with a try catch clause considered as a more efficient way than testing if the list is empty beforehand?Or is it the same? Thanks. P.S: If a similar question was previously asked on the forum please feel free to refer it.