Let's say you have 10 database records which you need to process in the following way:   1. Start   2. Pull 2 records from the database with the 'Processed' flag set to 'false'   3. Call the external web service with the custom data from this 2 records.   4. Update those 2 records in the database and set them as 'Processed' = 'true'   5. Goto 1 **Now, what can happen in this scenario?**   1. -   2. An error can occur while pulling the records from the database      * that's fine, as in the next round we will try to get them again.   3. An error can occur while calling an external web service      * that's also fine, as in the next round we will try to send those 2 records again   4. An error can occur while calling the database for the processed record update      * **what to do now?** Are you optimistic that this will never happen?      * keep in mind that you already sent those 2 records via web service and you must not send them again at any cost     * one option is to call a database update in a loop until it runs successfully !?   5. - **The question is, how (would) you handle this situation?** _**_**UPDATE**** Code illustration:               loop     {         db = database         ws = webservice              trans = db.open_transaction              recs = trans.query_for_two_records_and_update_processed_to_true              ws_response = ws.send_text_messages(recs)              if (ws_response == success)         {             trans.commit() // what would you do if this fails?         }         else         {             trans.rollback()         }     }